# Generated by Django 3.0 on 2020-02-10 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20200207_1813'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraddress',
            name='address_1',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='useraddress',
            name='address_2',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='useraddress',
            name='city',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='useraddress',
            name='company',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='useraddress',
            name='country',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='useraddress',
            name='fax',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='useraddress',
            name='phone_number',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='useraddress',
            name='postal_code',
            field=models.CharField(max_length=15),
        ),
    ]
