# Generated by Django 3.0 on 2019-12-06 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0007_auto_20191205_1859'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='description_short',
            field=models.TextField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='product',
            name='related_products',
            field=models.ManyToManyField(blank=True, related_name='_product_related_products_+', to='ecommerce.Product'),
        ),
        migrations.DeleteModel(
            name='Order',
        ),
    ]
