# Generated by Django 2.2.4 on 2019-12-10 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0010_remove_product_related_products'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='banner',
            field=models.ImageField(default='images/category/Category-banner.jpg', upload_to='images/category/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(default='images/product/product_default.jpg', upload_to='images/product/%Y/%m/%d'),
        ),
    ]
