# Generated by Django 3.0 on 2020-04-05 17:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0013_auto_20200405_2001'),
    ]

    operations = [
        migrations.AddField(
            model_name='productadditionalimage',
            name='product',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='product_images', to='ecommerce.Product'),
        ),
    ]
